### ISSUE TITLE
0.1.3.4 doesn't build on GHC 7.8

### ISSUE THREAD

**Issue by jonkri** [Philonous/d-bus#6]
```
Preprocessing executable 'dbus-introspect' for d-bus-0.1.3.4...
[1 of 1] Compiling Main             ( dbus-introspect/Main.hs, dist/dist-sandbox-6b08ff11/build/dbus-introspect/dbus-introspect-tmp/Main.o )

dbus-introspect/Main.hs:23:31: Not in scope: ‘<$>’
cabal: Error: some packages failed to install:
d-bus-0.1.3.4 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by Philonous** [comment]
7.8 is pretty old at this point (mid 2014), I think this has become irrelevant.
